# Generated by Django 3.0.4 on 2020-04-19 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnotsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnotsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnotsUrgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency_title', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnotsTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knot_topic', models.CharField(max_length=256, unique=True)),
                ('knot_topic_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Knots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knot_title', models.CharField(max_length=256)),
                ('knot_details', models.TextField(blank=True)),
                ('knot_url', models.URLField(blank=True)),
                ('knot_date', models.DateField(blank=True, null=True)),
                ('knot_time', models.TimeField(blank=True, null=True)),
                ('knot_image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('knot_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('knot_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('knot_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.KnotsCategory')),
                ('knot_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.UserProfile')),
                ('knot_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.KnotsStatus')),
                ('knot_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.KnotsTopics')),
                ('knot_urgency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.KnotsUrgency')),
            ],
        ),
    ]
