# Generated by Django 3.1 on 2020-09-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_auto_20200419_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knots',
            name='knot_category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskmanager.knotscategory'),
        ),
        migrations.AlterField(
            model_name='knots',
            name='knot_status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskmanager.knotsstatus'),
        ),
        migrations.AlterField(
            model_name='knots',
            name='knot_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskmanager.knotstopics'),
        ),
        migrations.AlterField(
            model_name='knots',
            name='knot_urgency',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskmanager.knotsurgency'),
        ),
    ]
